<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>05-Conditional Try Catch</title>
  </head>
  <body>
    <script>
      var arr = [1, 2, 3];
      try {
        try {
          // a(); // this causes error re-throw, outer catch will handle.
          arr.length = -1; // throw RangeError, inner catch will handle.
        } catch (e) {
          if (e instanceof RangeError) {
            console.log("Inner", e);
            // statement to handle this very common expected error
          } else {
            throw e; // re-throw the error as it is (without changing) - I don't know how to handle this, let outer catch to handle it.
          }
        }
      } catch (e) {
        console.log("Outer", e);
      }
    </script>
  </body>
</html>
